### ISSUE TITLE
How to add lemmy instances?

### ISSUE THREAD

**Issue by K0-RR** [PangoraWeb/pangora.social#2]
I noticed some servers are missing, for example in the "Regional" selection if you select Poland nothing happens.

Currently the only Polish instance is https://szmer.info/.

**Comment by Ategon** [comment]
Currently the only way for an instance to get added is by them requesting it and then I would manually add them. Im currently finishing up an update to automate that though so people can automatically add themselves.

I can do another comment here when done and ill be posting in the pangora p.d community

**Comment by Ategon** [comment]
Update has been pushed and instructions on how to get instances to show are in https://pangora.social/tags

Uses the fediseer tag system
